Ouderker_JonasHouse_1F_MapScripts::
	.byte 0

Ouderker_JonasHouse_1F_EventScript_Glacia::
	lock
	faceplayer
	msgbox Ouderker_JonasHouse_1F_Text_Glacia, MSGBOX_DEFAULT
	release
	end

Ouderker_JonasHouse_1F_EventScript_Scott::
	lock
	faceplayer
	msgbox Ouderker_JonasHouse_1F_Text_Scott, MSGBOX_DEFAULT
	release
	end

Ouderker_JonasHouse_1F_Text_Glacia:
	.string "Zo leuk dat Woel er ook was$"

Ouderker_JonasHouse_1F_Text_Scott:
	.string "HAHAHAH IK BEN MICHEL\n"
	.string "HAHAHAAH IK GA WATER OVER\l"
	.string "JE VRIENDEN HEENGOOIEN VAN\p"
	.string "HET BALKON LMAOO$"
