AmsterdamCentrum_MapScripts::
	.byte 0

AmsterdamCentrum_EventScript_AmsterdamCentrumSign::
	msgbox AmsterdamCentrum_Text_AmsterdamCentrumSign, MSGBOX_SIGN
	end

AmsterdamCentrum_EventScript_FritsFamHuisSign::
	msgbox AmsterdamCentrum_Text_FritsFamHuisSign, MSGBOX_SIGN
	end

AmsterdamCentrum_EventScript_MelkwegSign::
	msgbox AmsterdamCentrum_Text_MelkwegSign, MSGBOX_SIGN
	end

AmsterdamCentrum_EventScript_DrugslabSign::
	msgbox AmsterdamCentrum_Text_DrugslabSign, MSGBOX_SIGN
	end

AmsterdamCentrum_EventScript_Rechtboomsloot47DSign::
	msgbox AmsterdamCentrum_Text_Rechtboomsloot47DSign, MSGBOX_SIGN
	end

AmsterdamCentrum_Text_AmsterdamCentrumSign:
	.string "Amsterdam Centrum\n"
	.string "Kanker veel toeristen hier man$"

AmsterdamCentrum_Text_FritsFamHuisSign:
	.string "Frits' fam huis\n"
	.string "Frits, Frits' ma (niet dood)$"

AmsterdamCentrum_Text_MelkwegSign:
	.string "De Melkweg\n"
	.string "Vanavond Fiesta Macumba\l"
	.string "Beter hou je van Latina billen$"

AmsterdamCentrum_Text_DrugslabSign:
	.string "Drugslab\n"
	.string "Poeder te koop$"

AmsterdamCentrum_Text_Rechtboomsloot47DSign:
	.string "Rechtboomsloot 47D\n"
	.string "Nihao$"
